main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('shoes/', views.shoes_index, name='index'),
    path('about/', views.about, name='about'),
    path('shoes/<int:shoe_id>/', views.shoes_detail, name='detail'),
    path('shoes/create/', views.ShoeCreate.as_view(), name='shoes_create'),
    path('shoes/<int:pk>/update/', views.ShoeUpdate.as_view(), name='shoes_update'),
    path('shoes/<int:pk>/delete/', views.ShoeDelete.as_view(), name='shoes_delete'),
    path('shoes/<int:shoe_id>/add_recently_sold/', views.add_recently_sold, name='add_recently_sold'),
    path('shoes/<int:shoe_id>/assoc_store/<int:store_id>/', views.assoc_store, name='assoc_store'),
    path('shoes/<int:shoe_id>/unassoc_store/<int:store_id>/', views.unassoc_store, name='unassoc_store'),
    path('stores/', views.StoreList.as_view(), name='stores_index'),
    path('stores/<int:pk>/', views.StoreDetail.as_view(), name='stores_detail'),
    path('stores/create/', views.StoreCreate.as_view(), name='stores_create'),
    path('stores/<int:pk>/update/', views.StoreUpdate.as_view(), name='stores_update'),
    path('stores/<int:pk>/delete/', views.StoreDelete.as_view(), name='stores_delete'),
    path('accounts/signup/', views.signup, name='signup'),
]

shoecollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.
class Store(models.Model):
    name = models.CharField(max_length=100)
    url = models.CharField(max_length=250)
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('stores_detail', kwargs={'pk':self.id})

class Shoe(models.Model):
    name = models.CharField(max_length=100)
    brand = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    year = models.IntegerField()
    purchased_price = models.IntegerField()
    image_url = models.CharField(max_length=200, default='https://i.pinimg.com/originals/c4/ce/87/c4ce878870d075fcda7b6a40114f1757.gif')
    stores = models.ManyToManyField(Store)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('detail', kwargs={'shoe_id': self.id})
    
class Recently_Sold(models.Model):
    date = models.DateField('sold date')
    sold_price = models.IntegerField()
    shoe = models.ForeignKey(
        Shoe,
        on_delete=models.CASCADE
    )
    
    def __str__(self):
        return f"{self.sold_price} on {self.date}"

    class Meta:
        ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm
from .models import Recently_Sold

class Recently_SoldForm(ModelForm):
  class Meta:
    model = Recently_Sold
    fields = ['date', 'sold_price']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Shoe, Store, Recently_Sold
from .forms import Recently_SoldForm

# Create your views here.

def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

@login_required
def shoes_index(request):
    shoes = Shoe.objects.filter(user=request.user)
    return render(request, 'shoes/index.html', {'shoes': shoes})

@login_required
def shoes_detail(request, shoe_id):
    shoe = Shoe.objects.get(id=shoe_id)
    stores_shoe_isnt_available = Store.objects.exclude(id__in = shoe.stores.all().values_list('id'))
    recently_sold_form = Recently_SoldForm()
    urlshoe = shoe.name.replace(' ', '-')
    return render(request, 'shoes/detail.html', {
        'shoe': shoe,
        'recently_sold_form': recently_sold_form,
        'stores': stores_shoe_isnt_available,
        'urlshoe': urlshoe
        })
    
class ShoeCreate(CreateView, LoginRequiredMixin):
    model = Shoe
    fields = ['name', 'brand', 'description', 'year', 'purchased_price', 'image_url']
    
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
    
class ShoeUpdate(UpdateView, LoginRequiredMixin):
    model = Shoe
    fields = ['brand', 'description', 'year', 'purchased_price', 'image_url']

class ShoeDelete(DeleteView, LoginRequiredMixin):
    model = Shoe
    success_url = '/shoes/'

@login_required    
def assoc_store(request, shoe_id, store_id):
    shoe = Shoe.objects.get(id=shoe_id)
    shoe.stores.add(store_id)
    return redirect('detail', shoe_id=shoe_id)

@login_required
def unassoc_store(request, shoe_id, store_id):
  Shoe.objects.get(id=shoe_id).stores.remove(store_id)
  return redirect('detail', shoe_id=shoe_id)

@login_required
def add_recently_sold(request, shoe_id):
    form = Recently_SoldForm(request.POST)
    if form.is_valid():
        new_recently_sold = form.save(commit=False)
        new_recently_sold.shoe_id = shoe_id
        new_recently_sold.save()
    return redirect('detail', shoe_id=shoe_id)

class StoreList(ListView, LoginRequiredMixin):
    model = Store

class StoreDetail(DetailView, LoginRequiredMixin):
    model = Store

class StoreCreate(CreateView, LoginRequiredMixin):
    model = Store
    fields = '__all__'
    
class StoreUpdate(UpdateView, LoginRequiredMixin):
    model = Store
    fields = ['name', 'url']
    
class StoreDelete(DeleteView, LoginRequiredMixin):
    model = Storesuccess_url = '/stores/'
    
def signup(request):
  error_message = ''
  if request.method == 'POST':
    form = UserCreationForm(request.POST)
    if form.is_valid():
      user = form.save()
      #This is how we programmatically login
      login(request, user)
      return redirect('index')
    else:
      error_message = 'Invalid sign up - try again!'
  # A bad POST or it's a GET
  form = UserCreationForm()
  context = {
    'form': form,
    'error_message': error_message
  }
  return render(request, 'registration/signup.html', context)

main_app/templates/about.html
{% extends 'base.html' %}

{% block content %}

<h1>About</h1>
<hr />
<p>The Shoe Collector is a place for sneakerheads to collect their prized belongings, and keep track of current prices and stores!</p>


{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Shoe Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="/" class="left brand-logo">&nbsp;&nbsp;Shoe Collector</a></li>
        </ul>
        <ul class="right">
          <li><a href="/about">About</a></li>
          {% if user.is_authenticated %}
            <li><a href="{% url 'stores_create' %}">Add a Store</a></li>
            <li><a href="{% url 'stores_index' %}">View All Stores</a></li>
            <li><a href="{% url 'shoes_create' %}">Add a Shoe</a></li>
            <li><a href="/shoes">View All My Shoes</a></li>
            <li><a href="{% url 'logout' %}">Log Out</a></li>
          {% else %}
            <li><a href="{% url 'signup' %}">Sign Up</a></li>
            <li><a href="{% url 'login' %}">Log In</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2020 Shoe Collector &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1>Home</h1>
<p>Welcome to the Shoe Collector</p>
{% endblock %}

main_app/templates/main_app/shoe_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Shoe</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' shoe.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/shoe_form.html
{% extends 'base.html' %}

{% block content %}

  {% if object %}
    <h1>Edit <span class="teal-text">{{ object.name }}</span></h1>
  {% else %}
    <h1>Add Shoe</h1>
  {% endif %}

  <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" class="btn">
  </form>

{% endblock %}

main_app/templates/main_app/store_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Store</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'stores_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/store_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Store Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ store.name }}</span>
        <p>Website: <a href="{{ store.url }}">{{ store.url }}</a></p>
      </div>
      <div class="card-action">
        <a href="{% url 'stores_update' store.id %}">Edit</a>
        <a href="{% url 'stores_delete' store.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/store_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Store</h1>
  {% endif %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/store_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Store List</h1>

{% for store in store_list %}
  <a href="{% url 'stores_detail' store.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ store.name }}</span>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}

main_app/templates/shoes/detail.html
{% extends 'base.html' %}
{% block content %}
{% load app_filters %}
<h1>
    {{ shoe.name}} Details 
</h1>
<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <p>
          <img class="shoe-image" src={{ shoe.image_url }}>
          <span class="card-title">{{ shoe.name }}</span>
        </p>
        <p>Brand: {{ shoe.brand }}</p>
        <p>Description: {{ shoe.description }}</p>
        <p>Purchased Price: ${{ shoe.purchased_price}}
        {% if shoe.year > 0 %}
          <p>Year: {{ shoe.year }}</p>
        {% else %}
          <p>Year: NEW</p>
        {% endif %}
      </div>
      <div class="card-action">
        <a href="{% url 'shoes_update' shoe.id %}">Edit</a>
        <a href="{% url 'shoes_delete' shoe.id %}">Delete</a>
      </div>
    </div>
  </div>

  <div class="col s6">
    <form action="{% url 'add_recently_sold' shoe.id %}" method="post">
      {% csrf_token %}
      {{ recently_sold_form.as_p }}
      <input type="submit" class="btn" value="Add Recently Sold">
    </form>
    <table class="striped">
      <thead>
        <tr><th>Date</th><th>Sold Price</th></tr>
      </thead>
      <tbody>
        {% for recently_sold in shoe.recently_sold_set.all %}
          <tr>
            <td>{{recently_sold.date}}</td>
            <td>${{recently_sold.sold_price}}
            {% if recently_sold.sold_price > shoe.purchased_price %}
              <img class="ticker" src="https://i.imgur.com/6gyppCc.png">
              <span style="color:green"><small> + ${{recently_sold.sold_price|subtract:shoe.purchased_price}}</small></span>
            {% elif recently_sold.sold_price < shoe.purchased_price %}
              <img class="ticker" src="https://i.imgur.com/QfHTTIu.png">
              <span style="color:red"><small> - ${{shoe.purchased_price|subtract:recently_sold.sold_price}}</small></span>
            {% endif %}
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

<hr>
<div class="row">
  <div class="col s6">
    <h3>{{ shoe.name }} Available At</h3>
    {% if shoe.stores.count %}
      {% for store in shoe.stores.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              <div>{{ store.name }}</div>
              <a href="{{ store.url }}{{ urlshoe }}" target="_blank" >Check it out</a>
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'unassoc_store' shoe.id store.id %}" method="post">
                {% csrf_token %}
              <button type="submit" class="btn">Remove</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>No Available Stores :(</h5>
    {% endif %}
  </div>

  <div class="col s6">
    <h3>Stores</h3>
    {% if stores.count %}
      {% for store in stores.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              {{store.name}}
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'assoc_store' shoe.id store.id %}" method="post">
              {% csrf_token %}
              <button type="submit" class="btn">Add</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>{{shoe.name}} is already available in many stores</h5>
    {% endif %}
  </div>
</div>

<script>
  const dateEl = document.getElementById('id_date');
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });
</script>

{% endblock %}

main_app/templates/shoes/index.html
{% extends 'base.html' %}
{% block content %}
{% load app_filters %}

<h1>Shoe List</h1>
<p>You Currently Have: {{ shoes|length }} shoes in your collection</p>

{% for shoe in shoes %}
  <div class="card">
    <a href="{% url 'detail' shoe.id %}">
      <div class="card-content">
        <p>
        <img class="shoe-image" src={{ shoe.image_url }}>
        <span class="card-title">{{ shoe.name }}</span>
        </p>
        
      </div>
    </a>
  </div>
{% endfor %}

{% endblock %}